# change prefix to Ctrl-Space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# general settings
set -s escape-time 10           # address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g base-index 1             # start numbering at 1
set -g history-limit 50000      # increase scrollback buffer size from 2000 to 50000 lines
set -g display-time 3000        # increase tmux messages display duration from 750ms to 3s
set -g status-interval 5        # refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-left-length 50    # set longer session name in status bar
set -g status-keys emacs        # emacs key bindings in tmux command prompt, better than vi keys
set -g focus-events on          # focus events enabled for terminals that support them
set -g mouse on                 # capture and allow mouse bindings
set -g detach-on-destroy off    # switch to another session rather than detaching/exiting
setw -g mode-keys vi            # vi key bindings for copy/scroll mode

# color settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*:Tc'

# Rather than constraining window size to the max size of any client
# connected to the seession, constrain window size to the max size of any
# client connected to that window
setw -g aggressive-resize on

# easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# source .tmux.conf as suggested in `man tmux`
bind R source-file "~/.config/tmux/tmux.conf" \; display "Reloaded!"

# move between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize pane with vim keys
bind-key -r J resize-pane -D 10
bind-key -r K resize-pane -U 10
bind-key -r H resize-pane -L 10
bind-key -r L resize-pane -R 10

# create new panes/windows in the same directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# tmux-sessionizer popup on prefix+f
bind-key -r f display-popup -E -w 70% -h 70% "bash -c '~/.local/bin/tmux-sessionizer'"

# list of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# initialize tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
